[DSF-7703] ADA Timeout - logout announcement
claritymoney/xcore pull request #4
Opened 2021-04-19 15:46 UTC by emiclark

### Changelog
Added a timer to announce a warning 30 seconds before logout

2021-04-21 15:12 UTC, adeca requested changes

2021-04-21 15:12 UTC, adeca commented on Sources/Swift/Components/Dates and Timers/IdleTimer/IdleTimer+Gesture.swift
> +        private let timer2: InternalTimer
I suggest renaming `timer1` to `timer`, and `timer2` to `warningTimer` or `alertTimer`.

2021-04-21 15:12 UTC, adeca commented on Sources/Swift/Components/Dates and Timers/IdleTimer/IdleTimer+InternalTimer.swift
> +        private func handleVOAnnouncement() {
Posting the warning announcement should not be part of this class. This is just a generic timer which just calls an `onTimeout` block.

2021-04-23 15:28 UTC, adeca requested changes

2021-04-23 15:28 UTC, adeca commented on Sources/Swift/Components/Dates and Timers/IdleTimer/IdleTimer.swift
> +        public static func setUserInteractionTimeout(duration: TimeInterval? = nil, for window: UIWindow?) {
Lets revert this

2021-04-23 15:28 UTC, adeca commented on Sources/Swift/Components/Dates and Timers/IdleTimer/IdleTimer+Gesture.swift
> +    public func applicationWillTimeOutIdleTimerNotification(_ callback: @escaping () -> Void) -> NSObjectProtocol {
```suggestion
    public func applicationWillTimeOutUserInteraction(_ callback: @escaping () -> Void) -> NSObjectProtocol {
```
This makes it consistent with the `applicationDidTimeOutUserInteraction` method.

2021-04-23 15:28 UTC, adeca commented on Sources/Swift/Components/Dates and Timers/IdleTimer/IdleTimer+Gesture.swift
> +    public static var willTimeOutIdleTimerNotification: Notification.Name {
```suggestion
    public static var willTimeOutUserInteractionNotification: Notification.Name {
```
This makes it consistent with the `didTimeOutUserInteractionNotification` property.

2021-04-23 16:37 UTC, adeca approved these changes

2021-05-24 09:40 UTC, mstana commented on Sources/Swift/Components/Dates and Timers/IdleTimer/IdleTimer+InternalTimer.swift
> -
revert this change please

2021-05-24 09:44 UTC, mstana commented on Sources/Swift/Components/Dates and Timers/IdleTimer/IdleTimer+Gesture.swift
> +        private let warningTime: TimeInterval = 30 // seconds before voiceover announces the logout warning
```suggestion
        /// The timeout in seconds specifies the duration before the main `timer` notification is posted and will
        /// result in posting separate warning notification.
        private let warningTime: TimeInterval = 30
```

2021-07-01 19:33 UTC, mstana commented
We will handle this by https://github.com/claritymoney/xcore/pull/9

2021-07-01 19:33 UTC, closed without merging